version: "2"
services:
  prod:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: npm run serve
    volumes:
      - /usr/local/socialmoney-beta/backend-config/config.local.js:/usr/src/app/config/config.local.js
    ports:
      - 7009:7001
    networks:
      overlay:
  
  test:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: npm run dev
    volumes:
      - /usr/local/socialmoney-beta/backend-config/config.local.js:/usr/src/app/config/config.local.js
    ports:
      - 7009:7001
    networks:
      overlay:

  local:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    # command: npm run serve
    command: npm run dev
    volumes:
      - /usr/local/socialmoney-beta/backend-config/config.local.js:/usr/src/app/config/config.local.js
    ports:
      - 7009:7001
    networks:
      overlay:

networks:
  overlay: